version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
    - 7.3.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: chrono-node
    versions:
    - 2.2.0
    - 2.2.1
    - 2.2.3
    - 2.2.4
    - 2.2.5
  - dependency-name: "@emotion/styled"
    versions:
    - 11.1.5
  - dependency-name: react-scripts
    versions:
    - 4.0.2
