name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.1
      with:
        node-version: "14"
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test
