name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.3
      with:
        node-version: "20"
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test
