name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.1.0
      with:
        node-version: "20"
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test
